name: Run Benchmarks

on:
  schedule:
    - cron: "30 3 * * *"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  run-benchmarks:
    name: Run Benchmarks via Orchestrator
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to ACR
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Pull Orchestrator from ACR
        run: docker pull ${{ secrets.ACR_NAME }}.azurecr.io/container-orchestrator:latest

      - name: Run Orchestrator Container
        env:
          ACR_LOGIN_SERVER: ${{ vars.ACR_LOGIN_SERVER }}
          ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
          ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
          AZURE_BLOB_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_BLOB_STORAGE_CONNECTION_STRING }}
          AZURE_BLOB_STORAGE_BENCHMARK_CONTAINER: ${{ vars.AZURE_BLOB_STORAGE_BENCHMARK_CONTAINER }}
          AZURE_BLOB_STORAGE_METADATA_CONTAINER: ${{ vars.AZURE_BLOB_STORAGE_METADATA_CONTAINER }}
          POSTGRES_USERNAME: ${{ secrets.POSTGRES_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

        run: >
          docker run --rm
          -v "$HOME/.azure:/root/.azure"
          -e ACR_LOGIN_SERVER
          -e ACR_USERNAME
          -e ACR_PASSWORD
          -e AZURE_BLOB_STORAGE_CONNECTION_STRING
          -e AZURE_BLOB_STORAGE_BENCHMARK_CONTAINER
          -e AZURE_BLOB_STORAGE_METADATA_CONTAINER
          -e POSTGRES_USERNAME
          -e POSTGRES_PASSWORD
          ${{ secrets.ACR_NAME }}.azurecr.io/container-orchestrator:latest